### ISSUE TITLE
i can able to run iperf on remote machine but its runs with Server to server not connecting client IP 

### ISSUE THREAD

**Issue by panneerc** [iitggithub/iperf-web#3]
i can able to run iperf on remote machine but its runs with Server to server not connecting client IP 

can some help me please ??

**Comment by iitggithub** [comment]
The iperf-web docker image has changed pretty substantially as of today with lots of quality of life improvements and bug fixes.

Please pull the latest version from the docker repo and run the new version and try again.

```
sudo docker pull iitgdocker/iperf-web
sudo docker run --rm -p 5000:5000 iitgdocker/iperf-web
```

If you're running the container on your local machine, you can access the web interface by visiting http://127.0.0.1:5000 or just use the IP address of the client machine where the container is running.

Make sure you're able to connect from the host to host as well. You won't be able to perform an iperf test without connectivity.

Note that you do need a running iperf server in order to use this container.
